spring:
  application:
    name: shop-api
  datasource:
    url: jdbc:postgresql://localhost:5432/tickets
    username: postgres
    password: 183020
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "[hibernate.format_sql]": true

server:
  port: 8080
